version: "3"
services:
  gocloudproxy:
    build:
      context: .
      dockerfile: Dockerfile-local
    ports:
      - "8080:8080"
    environment:
      - "STORAGE_URL=${STORAGE_URL}"
      - "AZURE_STORAGE_ACCOUNT=${AZURE_STORAGE_ACCOUNT}"
      - "AZURE_STORAGE_KEY=${AZURE_STORAGE_KEY}"